name: jhentai
description: A flutter app for E-Hentai/EXHentai

publish_to: 'none'
version: 8.0.10+302

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.9.0
  get: ^4.7.2
  get_storage: ^2.1.1
  extended_nested_scroll_view: ^6.2.1
  html: ^0.15.6
  logger: 2.2.0
  flutter_rating_bar: 4.0.1
  waterfall_flow: ^3.1.1
  extended_image: ^10.0.1
  font_awesome_flutter: ^10.12.0
  intl: 0.20.2
  collection: 1.19.0
  clipboard: ^2.0.2
  # add _scrollToEnd and jumpTo
  scrollable_positioned_list: ^0.3.8
  flutter_list_view: ^1.1.29
  executor: ^2.2.5
  retry: 3.1.2
  path: 1.9.1
  drift: ^2.29.0
  sqlite3_flutter_libs: ^0.5.40
  path_provider: ^2.1.5
  flutter_slidable: ^3.1.2
  flutter_widget_from_html: ^0.17.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  desktop_webview_window: ^0.2.3
  photo_view: ^0.15.0
  zoom_view: ^0.0.24
  package_info_plus: ^9.0.0
  file_picker: ^10.3.3
  local_auth: ^3.0.0
  blur: ^4.0.2
  flutter_windowmanager_plus: 1.0.1
  animate_do: ^4.2.0
  share_plus: ^12.0.1
  syncfusion_flutter_charts: ^31.2.3
  archive: ^4.0.7
  fluttertoast: ^9.0.0
  battery_plus: ^7.0.0
  throttling: ^2.0.1
  receive_sharing_intent: ^1.8.1
  window_manager: ^0.5.1
  permission_handler: ^12.0.1
  grouped_list: ^6.0.0
  flutter_resizable_container: ^4.2.0
  loading_animation_widget: ^1.3.0
  simple_animations: ^5.2.0
  animated_flip_counter: ^0.3.4
  saver_gallery: ^3.0.6
  # fix build and namespace on android
  system_network_proxy: 
    git: 
      url: https://github.com/jiangtian616/system_network_proxy
      path: system_network_proxy
  http_proxy: ^1.2.3
  flutter_draggable_gridview: ^0.0.13
  flutter_displaymode: ^0.7.0
  pinput: ^5.0.2
  wakelock_plus: ^1.4.0
  flex_color_picker: ^3.7.1
  zoom_widget: 2.0.1
  android_intent_plus: ^6.0.0
  integral_isolates: ^0.5.1
  screen_brightness: ^2.1.7
  crypto: ^3.0.6
  csv: ^6.0.0
  dotted_border: ^3.1.0
  http_parser: ^4.1.2
  device_info_plus: ^12.2.0
  template_expressions: ^3.3.1+2
  uuid: 4.4.0
  xml: 6.5.0
  telegram: ^1.0.0
  json_annotation: ^4.9.0
  sqlite3: ^2.6.0
  local_auth_android: ^2.0.0
  local_auth_darwin: ^2.0.0
  local_auth_windows: ^2.0.0
  socks5_proxy: ^2.1.1
  
dependency_overrides:
  test_api: 0.6.0
  matcher: 0.12.16
  chewie: 1.7.0
  http: 1.1.0
  cached_network_image: 3.3.0
  collection: 1.19.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.26.3
  drift_dev: ^2.29.0
  build_runner: ^2.10.1
  frontend_server_client: 4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true